"use client";

import { useState } from "react";
import type { GapCard, Summary } from "@/types";

interface Props {
  gaps: GapCard[];
  summary: Summary | null;
}

export default function InvestmentMemo({ gaps, summary }: Props) {
  const [copied, setCopied] = useState(false);

  const topGap = gaps[0];
  const otherGaps = gaps.slice(1);

  function buildMemoText(): string {
    let text = "MARKET OPPORTUNITY BRIEF\n";
    text += `Generated by Blindspot\n`;
    text += "=".repeat(45) + "\n\n";

    if (summary) {
      text += "MARKET LANDSCAPE\n";
      text += `${summary.companies_found} companies identified, ${summary.complaints_found} customer pain points, ${summary.jobs_analyzed} job postings analyzed\n\n`;
    }

    if (topGap) {
      text += "TOP OPPORTUNITY\n";
      text += `${topGap.title}\n`;
      text += `Confidence: ${topGap.confidence.toFixed(1)}/10 | Opportunity: ${topGap.opportunity_size}\n\n`;
      text += `${topGap.description}\n\n`;

      text += "EVIDENCE\n";
      topGap.evidence?.forEach((e) => {
        text += `  - ${e.title}: ${e.snippet}\n`;
      });
      text += "\n";

      if (topGap.risk_flags?.length) {
        text += "RISK FLAGS\n";
        topGap.risk_flags.forEach((r) => {
          text += `  - ${r}\n`;
        });
        text += "\n";
      }
    }

    if (otherGaps.length) {
      text += "ADDITIONAL GAPS\n";
      otherGaps.forEach((gap, i) => {
        text += `  ${i + 2}. ${gap.title} — Confidence ${gap.confidence.toFixed(1)}/10\n`;
      });
    }

    return text;
  }

  async function copyToClipboard() {
    try {
      await navigator.clipboard.writeText(buildMemoText());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      const textarea = document.createElement("textarea");
      textarea.value = buildMemoText();
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }

  return (
    <div className="animate-fade_in">
      {/* Toolbar */}
      <div className="flex items-center justify-between mb-5">
        <h2 className="font-serif text-lg text-[var(--text-primary)]">Investment Memo</h2>
        <button
          onClick={copyToClipboard}
          className="text-xs px-3 py-1.5 rounded border border-[var(--border)] text-[var(--text-tertiary)]
                     hover:text-[var(--text-secondary)] hover:border-[var(--text-muted)]
                     transition-colors flex items-center gap-2"
        >
          {copied ? (
            <>
              <svg className="w-3.5 h-3.5 text-emerald-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
              Copied
            </>
          ) : (
            <>
              <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                  d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                />
              </svg>
              Copy
            </>
          )}
        </button>
      </div>

      {/* Memo Card */}
      <div className="rounded-lg border border-[var(--border)] bg-[var(--surface-raised)] overflow-hidden">
        {/* Header */}
        <div className="bg-[var(--text-primary)] px-6 py-4">
          <h3 className="font-serif text-base font-semibold text-[var(--surface)]">Market Opportunity Brief</h3>
          <p className="text-xs text-[var(--text-muted)] mt-1">Generated by Blindspot</p>
        </div>

        <div className="px-6 py-5 space-y-5">
          {/* Market Landscape */}
          {summary && (
            <section>
              <h4 className="text-[10px] font-medium uppercase tracking-[0.15em] text-[var(--text-muted)] mb-2">
                Market Landscape
              </h4>
              <p className="text-sm text-[var(--text-secondary)]">
                {summary.companies_found} companies identified, {summary.complaints_found} customer
                pain points, {summary.jobs_analyzed} job postings analyzed
              </p>
            </section>
          )}

          {/* Top Opportunity */}
          {topGap && (
            <section>
              <h4 className="text-[10px] font-medium uppercase tracking-[0.15em] text-[var(--text-muted)] mb-2">
                Top Opportunity
              </h4>
              <p className="text-sm font-medium text-[var(--text-primary)]">{topGap.title}</p>
              <div className="flex gap-3 mt-1.5 text-xs">
                <span className="text-emerald-400">
                  Confidence: {topGap.confidence.toFixed(1)}/10
                </span>
                <span className="text-[var(--text-muted)]">&bull;</span>
                <span className="text-[var(--text-tertiary)]">
                  {topGap.opportunity_size}
                </span>
              </div>
              <p className="text-sm text-[var(--text-tertiary)] mt-3 leading-relaxed">
                {topGap.description}
              </p>
            </section>
          )}

          {/* Evidence */}
          {topGap?.evidence && topGap.evidence.length > 0 && (
            <section>
              <h4 className="text-[10px] font-medium uppercase tracking-[0.15em] text-[var(--text-muted)] mb-2">
                Evidence
              </h4>
              <ul className="space-y-1.5">
                {topGap.evidence.map((e, i) => (
                  <li key={i} className="text-xs text-[var(--text-tertiary)] flex items-start gap-2">
                    <span className="text-[var(--text-muted)] mt-0.5 flex-none">&bull;</span>
                    <span>{e.snippet}</span>
                  </li>
                ))}
              </ul>
            </section>
          )}

          {/* Risk Flags */}
          {topGap?.risk_flags && topGap.risk_flags.length > 0 && (
            <section>
              <h4 className="text-[10px] font-medium uppercase tracking-[0.15em] text-[var(--text-muted)] mb-2">
                Risk Flags
              </h4>
              <ul className="space-y-1.5">
                {topGap.risk_flags.map((r, i) => (
                  <li key={i} className="text-xs text-amber-400 flex items-start gap-2">
                    <span className="text-amber-500 flex-none">!</span>
                    <span>{r}</span>
                  </li>
                ))}
              </ul>
            </section>
          )}

          {/* Additional Gaps */}
          {otherGaps.length > 0 && (
            <section className="border-t border-[var(--border)] pt-4">
              <h4 className="text-[10px] font-medium uppercase tracking-[0.15em] text-[var(--text-muted)] mb-2">
                Additional Gaps
              </h4>
              <ul className="space-y-2">
                {otherGaps.map((gap, i) => (
                  <li key={gap.id} className="text-xs text-[var(--text-tertiary)]">
                    <span className="text-[var(--text-muted)] mr-1.5">{i + 2}.</span>
                    <span className="text-[var(--text-secondary)] font-medium">{gap.title}</span>
                    <span className="text-[var(--text-muted)] ml-2">
                      {gap.confidence.toFixed(1)}/10
                    </span>
                  </li>
                ))}
              </ul>
            </section>
          )}
        </div>
      </div>
    </div>
  );
}
