/**
 * InvestmentMemo — VC-ready export view of the analysis.
 *
 * Reformats the same GapCard data into a format VCs actually use.
 * This is Improvement 4 from the plan — makes Cherry Ventures think
 * "I would actually use this output."
 *
 * Includes a "Copy to Clipboard" button for easy sharing.
 */
"use client";

import { useState } from "react";
import type { GapCard, Summary } from "@/types";

interface Props {
  gaps: GapCard[];
  summary: Summary | null;
}

export default function InvestmentMemo({ gaps, summary }: Props) {
  const [copied, setCopied] = useState(false);

  const topGap = gaps[0];
  const otherGaps = gaps.slice(1);

  function buildMemoText(): string {
    let text = "MARKET OPPORTUNITY BRIEF\n";
    text += `Generated by Blindspot\n`;
    text += "━".repeat(45) + "\n\n";

    if (summary) {
      text += "MARKET LANDSCAPE\n";
      text += `${summary.companies_found} companies identified, ${summary.complaints_found} customer pain points, ${summary.jobs_analyzed} job postings analyzed\n\n`;
    }

    if (topGap) {
      text += "TOP OPPORTUNITY\n";
      text += `${topGap.title}\n`;
      text += `Confidence: ${topGap.confidence.toFixed(1)}/10 | Opportunity: ${topGap.opportunity_size}\n\n`;
      text += `${topGap.description}\n\n`;

      text += "EVIDENCE\n";
      topGap.evidence?.forEach((e) => {
        text += `  - ${e.title}: ${e.snippet}\n`;
      });
      text += "\n";

      if (topGap.risk_flags?.length) {
        text += "RISK FLAGS\n";
        topGap.risk_flags.forEach((r) => {
          text += `  - ${r}\n`;
        });
        text += "\n";
      }
    }

    if (otherGaps.length) {
      text += "ADDITIONAL GAPS\n";
      otherGaps.forEach((gap, i) => {
        text += `  ${i + 2}. ${gap.title} — Confidence ${gap.confidence.toFixed(1)}/10\n`;
      });
    }

    return text;
  }

  async function copyToClipboard() {
    try {
      await navigator.clipboard.writeText(buildMemoText());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement("textarea");
      textarea.value = buildMemoText();
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }

  return (
    <div className="animate-fade_in">
      {/* Toolbar */}
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-sm font-medium text-neutral-300">Investment Memo</h2>
        <button
          onClick={copyToClipboard}
          className="text-xs px-3 py-1.5 rounded-md border border-neutral-700 text-neutral-300 hover:bg-neutral-800
                     transition-colors flex items-center gap-1.5"
        >
          {copied ? (
            <>
              <svg className="w-3.5 h-3.5 text-emerald-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
              Copied
            </>
          ) : (
            <>
              <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                  d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                />
              </svg>
              Copy to Clipboard
            </>
          )}
        </button>
      </div>

      {/* Memo Card */}
      <div className="bg-neutral-800/50 rounded-lg border border-neutral-700 overflow-hidden font-mono text-sm">
        {/* Header */}
        <div className="bg-white text-black px-6 py-4">
          <h3 className="font-semibold tracking-wide">MARKET OPPORTUNITY BRIEF</h3>
          <p className="text-neutral-500 text-xs mt-1">Generated by Blindspot</p>
        </div>

        <div className="px-6 py-5 space-y-5">
          {/* Market Landscape */}
          {summary && (
            <section>
              <h4 className="text-xs font-semibold text-neutral-500 uppercase tracking-wider mb-1.5">
                Market Landscape
              </h4>
              <p className="text-sm text-neutral-300">
                {summary.companies_found} companies identified, {summary.complaints_found} customer
                pain points, {summary.jobs_analyzed} job postings analyzed
              </p>
            </section>
          )}

          {/* Top Opportunity */}
          {topGap && (
            <section>
              <h4 className="text-xs font-semibold text-neutral-500 uppercase tracking-wider mb-1.5">
                Top Opportunity
              </h4>
              <p className="text-sm font-semibold text-white">{topGap.title}</p>
              <div className="flex gap-3 mt-1 text-xs">
                <span className="text-emerald-400">
                  Confidence: {topGap.confidence.toFixed(1)}/10
                </span>
                <span className="text-neutral-600">|</span>
                <span className="text-neutral-400">
                  Opportunity: {topGap.opportunity_size}
                </span>
              </div>
              <p className="text-sm text-neutral-400 mt-2 leading-relaxed">
                {topGap.description}
              </p>
            </section>
          )}

          {/* Evidence */}
          {topGap?.evidence && topGap.evidence.length > 0 && (
            <section>
              <h4 className="text-xs font-semibold text-neutral-500 uppercase tracking-wider mb-1.5">
                Evidence
              </h4>
              <ul className="space-y-1">
                {topGap.evidence.map((e, i) => (
                  <li key={i} className="text-xs text-neutral-400">
                    <span className="text-neutral-600 mr-1">&bull;</span>
                    {e.snippet}
                  </li>
                ))}
              </ul>
            </section>
          )}

          {/* Risk Flags */}
          {topGap?.risk_flags && topGap.risk_flags.length > 0 && (
            <section>
              <h4 className="text-xs font-semibold text-neutral-500 uppercase tracking-wider mb-1.5">
                Risk Flags
              </h4>
              <ul className="space-y-1">
                {topGap.risk_flags.map((r, i) => (
                  <li key={i} className="text-xs text-red-400">
                    <span className="text-red-600 mr-1">&bull;</span>
                    {r}
                  </li>
                ))}
              </ul>
            </section>
          )}

          {/* Additional Gaps */}
          {otherGaps.length > 0 && (
            <section className="border-t border-neutral-700 pt-4">
              <h4 className="text-xs font-semibold text-neutral-500 uppercase tracking-wider mb-1.5">
                Additional Gaps
              </h4>
              <ul className="space-y-1">
                {otherGaps.map((gap, i) => (
                  <li key={gap.id} className="text-xs text-neutral-400">
                    <span className="text-neutral-600 mr-1">{i + 2}.</span>
                    <span className="font-medium text-white">{gap.title}</span>
                    <span className="text-neutral-500">
                      {" "}— Confidence {gap.confidence.toFixed(1)}/10
                    </span>
                  </li>
                ))}
              </ul>
            </section>
          )}
        </div>
      </div>
    </div>
  );
}
