"use client";

import { useState } from "react";
import type { GapCard, Summary } from "@/types";
import { BlurFade } from "@/components/ui/blur-fade";
import { Copy, Check } from "lucide-react";

interface Props {
  gaps: GapCard[];
  summary: Summary | null;
}

export default function InvestmentMemo({ gaps, summary }: Props) {
  const [copied, setCopied] = useState(false);

  const topGap = gaps[0];
  const otherGaps = gaps.slice(1);

  function buildMemoText(): string {
    let text = "MARKET OPPORTUNITY BRIEF\n";
    text += `Generated by Blindspot\n`;
    text += "=".repeat(45) + "\n\n";

    if (summary) {
      text += "MARKET LANDSCAPE\n";
      text += `${summary.companies_found} companies identified, ${summary.complaints_found} customer pain points, ${summary.jobs_analyzed} job postings analyzed\n\n`;
    }

    if (topGap) {
      text += "TOP OPPORTUNITY\n";
      text += `${topGap.title}\n`;
      text += `Confidence: ${topGap.confidence.toFixed(1)}/10 | Opportunity: ${topGap.opportunity_size}\n\n`;
      text += `${topGap.description}\n\n`;

      text += "EVIDENCE\n";
      topGap.evidence?.forEach((e) => {
        text += `  - ${e.title}: ${e.snippet}\n`;
      });
      text += "\n";

      if (topGap.risk_flags?.length) {
        text += "RISK FLAGS\n";
        topGap.risk_flags.forEach((r) => {
          text += `  - ${r}\n`;
        });
        text += "\n";
      }
    }

    if (otherGaps.length) {
      text += "ADDITIONAL GAPS\n";
      otherGaps.forEach((gap, i) => {
        text += `  ${i + 2}. ${gap.title} — Confidence ${gap.confidence.toFixed(1)}/10\n`;
      });
    }

    return text;
  }

  async function copyToClipboard() {
    try {
      await navigator.clipboard.writeText(buildMemoText());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      const textarea = document.createElement("textarea");
      textarea.value = buildMemoText();
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }

  return (
    <div>
      {/* Toolbar */}
      <BlurFade delay={0} duration={0.3}>
        <div className="flex items-center justify-between mb-5">
          <h2 className="font-serif text-lg text-[var(--text-primary)]">Investment Memo</h2>
          <button
            onClick={copyToClipboard}
            className="text-xs px-3 py-1.5 rounded-lg border border-[var(--border)] text-[var(--text-tertiary)]
                       hover:text-[var(--text-secondary)] hover:border-[var(--text-muted)]
                       transition-all duration-200 flex items-center gap-2"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-500" />
                Copied
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                Copy
              </>
            )}
          </button>
        </div>
      </BlurFade>

      {/* Memo Card */}
      <BlurFade delay={0.08} duration={0.4}>
        <div className="rounded-xl border border-[var(--border)] bg-[var(--surface-raised)] overflow-hidden">
          {/* Header */}
          <div className="bg-[var(--text-primary)] px-6 py-4">
            <h3 className="font-serif text-base font-semibold text-[var(--surface)]">Market Opportunity Brief</h3>
            <p className="text-xs text-[var(--text-muted)] mt-1">Generated by Blindspot</p>
          </div>

          <div className="px-6 py-5 space-y-5">
            {/* Market Landscape */}
            {summary && (
              <BlurFade delay={0.15} duration={0.3}>
                <section>
                  <h4 className="text-[10px] font-medium uppercase tracking-[0.15em] text-[var(--text-muted)] mb-2">
                    Market Landscape
                  </h4>
                  <p className="text-sm text-[var(--text-secondary)]">
                    {summary.companies_found} companies identified, {summary.complaints_found} customer
                    pain points, {summary.jobs_analyzed} job postings analyzed
                  </p>
                </section>
              </BlurFade>
            )}

            {/* Top Opportunity */}
            {topGap && (
              <BlurFade delay={0.2} duration={0.3}>
                <section>
                  <h4 className="text-[10px] font-medium uppercase tracking-[0.15em] text-[var(--text-muted)] mb-2">
                    Top Opportunity
                  </h4>
                  <p className="text-sm font-medium text-[var(--text-primary)]">{topGap.title}</p>
                  <div className="flex gap-3 mt-1.5 text-xs">
                    <span className="text-emerald-400">
                      Confidence: {topGap.confidence.toFixed(1)}/10
                    </span>
                    <span className="text-[var(--text-muted)]">&bull;</span>
                    <span className="text-[var(--text-tertiary)]">
                      {topGap.opportunity_size}
                    </span>
                  </div>
                  <p className="text-sm text-[var(--text-tertiary)] mt-3 leading-relaxed">
                    {topGap.description}
                  </p>
                </section>
              </BlurFade>
            )}

            {/* Evidence */}
            {topGap?.evidence && topGap.evidence.length > 0 && (
              <BlurFade delay={0.25} duration={0.3}>
                <section>
                  <h4 className="text-[10px] font-medium uppercase tracking-[0.15em] text-[var(--text-muted)] mb-2">
                    Evidence
                  </h4>
                  <ul className="space-y-1.5">
                    {topGap.evidence.map((e, i) => (
                      <li key={i} className="text-xs text-[var(--text-tertiary)] flex items-start gap-2">
                        <span className="text-[var(--text-muted)] mt-0.5 flex-none">&bull;</span>
                        <span>{e.snippet}</span>
                      </li>
                    ))}
                  </ul>
                </section>
              </BlurFade>
            )}

            {/* Risk Flags */}
            {topGap?.risk_flags && topGap.risk_flags.length > 0 && (
              <BlurFade delay={0.3} duration={0.3}>
                <section>
                  <h4 className="text-[10px] font-medium uppercase tracking-[0.15em] text-[var(--text-muted)] mb-2">
                    Risk Flags
                  </h4>
                  <ul className="space-y-1.5">
                    {topGap.risk_flags.map((r, i) => (
                      <li key={i} className="text-xs text-amber-400/80 flex items-start gap-2">
                        <span className="text-amber-500/70 flex-none">!</span>
                        <span>{r}</span>
                      </li>
                    ))}
                  </ul>
                </section>
              </BlurFade>
            )}

            {/* Additional Gaps */}
            {otherGaps.length > 0 && (
              <BlurFade delay={0.35} duration={0.3}>
                <section className="border-t border-[var(--border)] pt-4">
                  <h4 className="text-[10px] font-medium uppercase tracking-[0.15em] text-[var(--text-muted)] mb-2">
                    Additional Gaps
                  </h4>
                  <ul className="space-y-2">
                    {otherGaps.map((gap, i) => (
                      <li key={gap.id} className="text-xs text-[var(--text-tertiary)]">
                        <span className="text-[var(--text-muted)] mr-1.5">{i + 2}.</span>
                        <span className="text-[var(--text-secondary)] font-medium">{gap.title}</span>
                        <span className="text-[var(--text-muted)] ml-2">
                          {gap.confidence.toFixed(1)}/10
                        </span>
                      </li>
                    ))}
                  </ul>
                </section>
              </BlurFade>
            )}
          </div>
        </div>
      </BlurFade>
    </div>
  );
}
