import type { GapCard, Summary } from "@/types";

export function buildMemoText(gaps: GapCard[], summary: Summary | null): string {
  const topGap = gaps[0];
  const otherGaps = gaps.slice(1);

  let text = "MARKET OPPORTUNITY BRIEF\n";
  text += `Generated by Blindspot\n`;
  text += "=".repeat(45) + "\n\n";

  if (summary) {
    text += "MARKET LANDSCAPE\n";
    text += `${summary.companies_found} companies identified, ${summary.complaints_found} customer pain points, ${summary.jobs_analyzed} job postings analyzed\n\n`;
  }

  if (topGap) {
    text += "TOP OPPORTUNITY\n";
    text += `${topGap.title}\n`;
    text += `Confidence: ${topGap.confidence.toFixed(1)}/10 | Opportunity: ${topGap.opportunity_size}\n\n`;
    text += `${topGap.description}\n\n`;

    text += "EVIDENCE\n";
    topGap.evidence?.forEach((e) => {
      text += `  - ${e.title}: ${e.snippet}\n`;
    });
    text += "\n";

    if (topGap.risk_flags?.length) {
      text += "RISK FLAGS\n";
      topGap.risk_flags.forEach((r) => {
        text += `  - ${r}\n`;
      });
      text += "\n";
    }
  }

  if (otherGaps.length) {
    text += "ADDITIONAL GAPS\n";
    otherGaps.forEach((gap, i) => {
      text += `  ${i + 2}. ${gap.title} — Confidence ${gap.confidence.toFixed(1)}/10\n`;
    });
  }

  return text;
}
